server:
  port: 3000
spring:
  application:
    name: redis-provider
  redis:
    host: 192.168.72.139
eureka:
  client:
    service-url:
      dafaultZone: http://localhost:1000/eureka
  instance:
    prefer-ip-address: true
